artifacts_root: Artifacts

Data_Ingestion:
  dir: Artifacts/data_ingestion
  url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip
  local_dir: Artifacts/data_ingestion/zip_data/data.zip
  unzip_dir: Artifacts/data_ingestion/data  

Data_Transformation:
  dir: Artifacts/data_transformation
  data_path: Artifacts\data_ingestion\data\samsum_dataset
  tokenizer: microsoft/Phi-3-mini-4k-instruct
  transform_data: Artifacts/data_transformation
  
Model_Trainer:
  dir: Artifacts/model_Trainer
  data_path: Artifacts\data_transformation\transform
  model: microsoft/Phi-3-mini-4k-instruct
