artifacts_root: Artifacts

Data_Ingestion:
  dir: Artifacts/data_ingestion
  url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip
  local_dir: Artifacts/data_ingestion/zip_data/data.zip
  unzip_dir: Artifacts/data_ingestion/data  

Data_Transformation:
  dir: Artifacts/data_transformation
  data_path: Artifacts\data_ingestion\data\samsum_dataset
  tokenizer: google/pegasus-cnn_dailymail

  
Model_Trainer:
  dir: Artifacts/model_Trainer
  data_path: Artifacts\data_transformation\samsum_dataset
  model: google/pegasus-cnn_dailymail
